/**
 * Art-Net Protocol Constants
 */

// Protocol Version
const PROTOCOL_VERSION_HI = 0;
const PROTOCOL_VERSION_LO = 14; // Art-Net 4

// Art-Net Standard
const ARTNET_PORT = 6454;
const ARTNET_BROADCAST = "255.255.255.255";
const ARTNET_TIMEOUT = 2500; // 2.5 seconds in milliseconds

// DMX
const DMX_CHANNELS = 512;
const DMX_START_CODE = 0x00;

// Universe
const UNIVERSES_PER_SUBNET = 16;
const SUBNETS_PER_NET = 16;
const UNIVERSES_PER_NET = UNIVERSES_PER_SUBNET * SUBNETS_PER_NET;

// Port Address
const PORT_ADDRESS_MAX = 0x7FFF; // 15 bits (32768 addresses)

// Sequence
const SEQUENCE_DISABLE = 0x00;
const SEQUENCE_MIN = 0x01;
const SEQUENCE_MAX = 0xFF;

// RDM
const RDM_DRAFT = 0x00;
const RDM_STANDARD = 0x01;

module.exports = {
  PROTOCOL_VERSION_HI,
  PROTOCOL_VERSION_LO,
  ARTNET_PORT,
  ARTNET_BROADCAST,
  ARTNET_TIMEOUT,
  DMX_CHANNELS,
  DMX_START_CODE,
  UNIVERSES_PER_SUBNET,
  SUBNETS_PER_NET,
  UNIVERSES_PER_NET,
  PORT_ADDRESS_MAX,
  SEQUENCE_DISABLE,
  SEQUENCE_MIN,
  SEQUENCE_MAX,
  RDM_DRAFT,
  RDM_STANDARD,
};
